#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v4
# autospec commit: f4bef72
#
Name     : R-eRm
Version  : 1.0.6
Release  : 48
URL      : https://cran.r-project.org/src/contrib/eRm_1.0-6.tar.gz
Source0  : https://cran.r-project.org/src/contrib/eRm_1.0-6.tar.gz
Summary  : Extended Rasch Modeling
Group    : Development/Tools
License  : GPL-3.0
Requires: R-eRm-lib = %{version}-%{release}
Requires: R-colorspace
Requires: R-psych
BuildRequires : R-colorspace
BuildRequires : R-psych
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-eRm package.
Group: Libraries

%description lib
lib components for the R-eRm package.


%prep
%setup -q -n eRm
pushd ..
cp -a eRm buildavx2
popd
pushd ..
cp -a eRm buildavx512
popd
pushd ..
cp -a eRm buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1710611211

%install
export SOURCE_DATE_EPOCH=1710611211
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-va/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/eRm/CITATION
/usr/lib64/R/library/eRm/DESCRIPTION
/usr/lib64/R/library/eRm/INDEX
/usr/lib64/R/library/eRm/Meta/Rd.rds
/usr/lib64/R/library/eRm/Meta/data.rds
/usr/lib64/R/library/eRm/Meta/features.rds
/usr/lib64/R/library/eRm/Meta/hsearch.rds
/usr/lib64/R/library/eRm/Meta/links.rds
/usr/lib64/R/library/eRm/Meta/nsInfo.rds
/usr/lib64/R/library/eRm/Meta/package.rds
/usr/lib64/R/library/eRm/Meta/vignette.rds
/usr/lib64/R/library/eRm/NAMESPACE
/usr/lib64/R/library/eRm/NEWS.Rd
/usr/lib64/R/library/eRm/NEWS.pdf
/usr/lib64/R/library/eRm/NEWSRd2txt.R
/usr/lib64/R/library/eRm/R/eRm
/usr/lib64/R/library/eRm/R/eRm.rdb
/usr/lib64/R/library/eRm/R/eRm.rdx
/usr/lib64/R/library/eRm/data/Rdata.rdb
/usr/lib64/R/library/eRm/data/Rdata.rds
/usr/lib64/R/library/eRm/data/Rdata.rdx
/usr/lib64/R/library/eRm/doc/eRm.R
/usr/lib64/R/library/eRm/doc/eRm.Rnw
/usr/lib64/R/library/eRm/doc/eRm.pdf
/usr/lib64/R/library/eRm/doc/index.html
/usr/lib64/R/library/eRm/help/AnIndex
/usr/lib64/R/library/eRm/help/aliases.rds
/usr/lib64/R/library/eRm/help/eRm.rdb
/usr/lib64/R/library/eRm/help/eRm.rdx
/usr/lib64/R/library/eRm/help/paths.rds
/usr/lib64/R/library/eRm/html/00Index.html
/usr/lib64/R/library/eRm/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/eRm/libs/eRm.so
/V4/usr/lib64/R/library/eRm/libs/eRm.so
/VA/usr/lib64/R/library/eRm/libs/eRm.so
/usr/lib64/R/library/eRm/libs/eRm.so
